### ISSUE TITLE
swash of error messages on saving edits

### ISSUE THREAD

**Issue by Konfekt** [stefandtw/quickfix-reflector.vim#17] opened 2016-06-04 09:52 UTC
In a file t.tex, and a single line in the qf-window that matches line 98 and well exists, saving the edits produces
```vim
"t.tex" 804 lines --19%--

replace with \\K (y/n/a/q/l/^E/^Y)?
5 substitutions on 1 line
Error detected while processing function <SNR>174_OnWrite:
line   31:
E684: list index out of range: 0
E116: Invalid arguments for function index(qfBufferLines, matchList[0]))
E116: Invalid arguments for function remove
line   33:
E684: list index out of range: 1
E116: Invalid arguments for function escape(matchList[1], '/\')
E15: Invalid expression: '\C\V\^' . escape(matchList[1], '/\')
line   37:
E684: list index out of range: 1
E116: Invalid arguments for function escape(matchList[1], '/\') . '\(' . qfDescriptionEscaped . escape(matchList[2], '/\') . '\$' . '\)\@\!\(\.\*\)\$'
E15: Invalid expression: '\C\V\^' . escape(matchList[1], '/\') . '\(' . qfDescriptionEscaped . escape(matchList[2], '/\') . '\$' . '\)\@\!\(\.\*\)\$'
line   40:
E716: Key not present in Dictionary: markerPatternForChanges, 'cnw')
E116: Invalid arguments for function search(entry.markerPatternForChanges, 'cnw')
E15: Invalid expression: search(entry.markerPatternForChanges, 'cnw')
line   41:
E121: Undefined variable: lineNumberForChange
E15: Invalid expression: lineNumberForChange && entry.valid == 1
line   53:
E716: Key not present in Dictionary: markerPattern, 'cnw')
E116: Invalid arguments for function search(entry.markerPattern, 'cnw')
E15: Invalid expression: search(entry.markerPattern, 'cnw')
line   54:
E121: Undefined variable: lineNumber
E15: Invalid expression: !lineNumber
line   58:
E121: Undefined variable: lineNumber
E15: Invalid expression: lineNumber
```

**Comment by stefandtw** [comment] 2016-06-04 10:47
To reproduce this, please provide that line of text and what you tried to replace it with.

**Comment by Konfekt** [comment] 2016-06-04 19:48
The line is
```tex
Let $V = T \ox_{\o_\K} \K$ be the associated finite-dimensional $\L$ vector space on which $\cG_{\Q_p}$ acts continuously and $\rD(V) = \rD(T) \ox_{\o_\L} \L$ its corresponding étale $\varphi,\Gamma$-module over $\cE_\L$.
```
and
```vim
:%substitute:\\L:\\K:cgI
```

**Comment by stefandtw** [comment] 2016-06-05 08:25
I can't reproduce the errors. If you want to help break it down, you could:

* Confirm it has nothing to do with the rest of the file. Make a new file containing only the one line you wish to replace and confirm that the errors happen again.
* Confirm it has nothing to do with your Vim configuration. Start `vim -u NONE`, manually `:source <path>/quickfix-reflector.vim` and confirm that the errors happen again.
* Make a screenshot of the quickfix window before the replacement.
* Provide the output of `vim --version`

**Comment by Konfekt** [comment] 2016-06-06 08:46
I am sorry, the line was incorrectly pasted. It is:
```tex
  Let $V = T \ox_{\o_\L} \L$ be the associated finite-dimensional $\L$ vector space on which $\cG_{\Q_p}$ acts continuously and $\rD(V) = \rD(T) \ox_{\o_\L} \L$ its corresponding étale $\varphi,\Gamma$-module over $\cE_\L$.
``
The sole difference being the indent of two white spaces. Without indent, it not reproducible over here neither.

**Comment by stefandtw** [comment] 2016-06-06 19:35
Should be fixed now. Thanks for reporting.

**Closed by stefandtw** 2016-06-06 19:35 UTC
